# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
# title: J's homepage
# description: Bookmark this to keep an eye on my project updates!

<html>

<body>
  <h1>YOUR NAME</h1>
  <p>Welcome to my website!</p>
  <img src="https://content.codecademy.com/articles/github-pages-via-web-app/happy-ice-cream.gif" />
</body>

</html>
